apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  labels: 
    type: local
    app: restheart-mongo-volume
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs_shares/k8s/data"
