apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: restheart-mongo-volume
  name: restheart-mongo-volume
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
